Models/DemoAppDBContext.cs
using Microsoft.EntityFrameworkCore;

namespace DemoAppMVC.Models
{
    public class DemoAppDBContext : DbContext
    {
        public DemoAppDBContext(DbContextOptions<DemoAppDBContext> opts) : base(opts)
        {
        }


            public DbSet<Staff> Staffs { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace DemoAppMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Staff.cs
namespace DemoAppMVC.Models
{
    public class Staff
    {
        public int Id { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
        public int Age { get; set; }
        

    }
}

Controllers/HomeController.cs
using DemoAppMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DemoAppMVC.Controllers
{
    public class HomeController : Controller
    {
        private const string V = "Anything";
        private const string viewdata = "Davido";
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About()
        {
            /*string address = "Lagos";*/
            ViewBag.Header = V;
            ViewData["singer"] = viewdata;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StaffController.cs
using DemoAppMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using System.Windows;

namespace DemoAppMVC.Controllers
{
    public class StaffController : Controller
    {
        /*static int Id = 1;
        static List<Staff> staffList = new List<Staff>();*/
        private DemoAppDBContext context;
        public StaffController(DemoAppDBContext demoAppDBContext)
        {
            context = demoAppDBContext;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult List()
        {
            List<Staff> staffList = context.Staffs.ToList();
            return View(staffList);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(string FirstName, string LastName, int Age)
        {
            Staff staff = new Staff()
            {
                FirstName = FirstName,
                LastName = LastName,
                Age = Age
            };
           
            context.Staffs.Add(staff);
            context.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult ViewStaff(int id)
        {
            Staff staff = context.Staffs.Find(id);
             
            return View(staff);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Staff staff = context.Staffs.Find(id);

            return View(staff);
        }

        [HttpPost]
        public IActionResult EditStaff(int Id, string FirstName, string LastName, int Age)
        {
            Staff? staffToUpdate = context.Staffs.Find(Id);

            if (staffToUpdate == null)
            {
                return RedirectToAction("Error");
            }
            staffToUpdate.FirstName = FirstName;
            staffToUpdate.LastName = LastName;
            staffToUpdate.Age = Age;

            context.Staffs.Update(staffToUpdate);
            context.SaveChanges();

            return RedirectToAction("List");
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            Staff? staffToDelete = context.Staffs.Find(Id);

            if(staffToDelete == null)
            {
                return RedirectToAction("Error");
            }
            context.Staffs.Remove(staffToDelete);
            context.SaveChanges();
            return RedirectToAction("List");
        }

        public IActionResult Error()
        {
            return View();
        }
    }

    }

Views/Home/About.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string name = "Samuel";
    int age = 19;
}

@if(age >= 18)
{
    <p>@name is of age</p>
}

else
{
    <p style="color: red">I am sorry, @name is underage</p>
}

<h1>This is @name's About page</h1>
<h2>The header is @ViewBag.Header</h2>
<h3>The musician's name is @ViewData["singer"]</h3>
<h4>The address for the training is </h4>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoAppMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoAppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DemoAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_StaffLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DemoAppMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoAppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="List">List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DemoAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Staff/Create.cshtml
@{
    ViewData["Title"] = "Create Staff Profile";
}

<style>
    .bg-image {
        background-image: url('https://th.bing.com/th/id/R.39ee609d2381b1246bf0580f7740f69f?rik=uWfvRen2526XBQ&riu=http%3a%2f%2fak3.picdn.net%2fshutterstock%2fvideos%2f3644588%2fthumb%2f1.jpg%3fi10c%3dimg.resize(height%3a160)&ehk=3lzP8SotVUTHlmAYI2IFXcwlchIBkTqXudwQSLUHtww%3d&risl=&pid=ImgRaw&r=0');
        background-size: cover;
        background-position: center;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
    }

    .bg-overlay {
        background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5));
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
    }
</style>

<div class="bg-image"></div>
<div class="bg-overlay"></div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-5">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header">
                    <h3 class="text-center font-weight-light my-4">Create A New Staff Profile</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="Staff" asp-action="Register" method="post">
                        <div class="form-row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="small mb-1" for="firstName">First Name</label>
                                    <input class="form-control py-2" id="firstName" type="text" placeholder="Enter First Name" name="FirstName" />
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="small mt-3" for="lastName">Last Name</label>
                                    <input class="form-control py-2" id="lastName" type="text" placeholder="Enter Last Name" name="LastName" />
                                </div>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label class="small mt-3" for="age">Age</label>
                                    <input class="form-control py-2" id="age" type="number" placeholder="Enter Age" name="Age" />
                                </div>
                            </div>
                        </div>
                        <div class="form-group mt-4 mb-0">
                            <button type="submit" class="btn  btn-sm btn-success btn-block">Save</button>
                        </div>
                    </form>
                </div>
                <div class="card-footer text-center">
                    <div class="small"><a href="/">Back to Homepage</a></div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Staff/Edit.cshtml
@{
}

@model Staff


@{
    try
    {
        if(!(@Model.FirstName == null || Model.LastName == null))
        {
            <h2>Edit information for @Model.FirstName @Model.LastName</h2>
        }
        <form asp-controller="Staff" asp-action="EditStaff" method="post">
            <label>FirstName: </label><br />
            <input value="@Model.FirstName" type="text" name="FirstName" /><br /><br />
            <label>LastName: </label><br />
            <input value="@Model.LastName" type="text" name="LastName" /><br /><br />
            <label>Age: </label><br />
            <input value="@Model.Age" type="number" name="Age" /><br /><br />
            <input type="hidden" name="Id" value="@Model.Id" />

            <input type="submit" value="Save Changes" class="btn-warning" /><br /><br />

        </form>
    }    catch (NullReferenceException ex)
    {
        <h3>No staff exists with this ID</h3>
        <p>Go back to <a asp-controller="Staff" asp-action="List">List</a></p>
    }  
}

Views/Staff/Index.cshtml
@{
    ViewData["Title"] = "Home";
}



<div class="container-fluid">
    <div class="jumbotron jumbotron-fluid text-center bg-primary text-white">
        <div class="container">
            <h1 class="display-4">Welcome to Staff Management System!</h1>
            <p class="lead">Manage your staff efficiently with our platform.</p>
            <a href="/Staff/Create" class="btn btn-sm mb-3 btn-light">Create Staff Profile</a>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card mb-4">
                <img src="https://th.bing.com/th/id/OIP.IH7V3bSReNbJK5eUx8nXNAHaE8?w=927&h=618&rs=1&pid=ImgDetMain" class="card-img-top" alt="Image">
                <div class="card-body">
                    <h5 class="card-title">Employee Management</h5>
                    <p class="card-text">Efficiently manage employee data, including personal details, roles, and schedules.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4">
                <img src="https://th.bing.com/th/id/OIP.grieTn1ZXnD9YbDZ6JLbTwHaGw?w=850&h=775&rs=1&pid=ImgDetMain" class="card-img-top" alt="Image">
                <div class="card-body">
                    <h5 class="card-title">Attendance Tracking</h5>
                    <p class="card-text">Track employee attendance and generate attendance reports seamlessly.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card mb-4">
                <img src=https://th.bing.com/th/id/OIP.L--ejAMtEYclobboenz2FgHaE8?rs =1&pid =ImgDetMain" class="card-img-top" alt="Image">
                <div class="card-body">
                    <h5 class="card-title">Performance Evaluation</h5>
                    <p class="card-text">Conduct performance evaluations and set goals for staff members.</p>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Staff/List.cshtml
@{
}
@model List<Staff>

<h1>This is the List page for Staff</h1>

<table class="table table-bordered table-hover table-dark">
    <tr>
        <th>ID</th>
        <th>FIRST NAME</th>
        <th>LAST NAME</th>
        <th>AGE</th>
        <th>ACTION</th>
    </tr>
    
        @foreach(Staff staff in Model)
        {
            <tr>
                <td>@staff.Id</td>
                <td>@staff.FirstName</td>
                <td>@staff.LastName</td>
                <td>@staff.Age</td>
                <td>
                    <a class="btn btn-primary btn-sm" asp-controller="Staff" asp-action="ViewStaff" asp-route-id="@staff.Id">View</a>
                    <a class="btn btn-warning btn-sm" asp-controller="Staff" asp-action="Edit" asp-route-id="@staff.Id">Edit</a>
                    <a class="btn btn-danger btn-sm" asp-controller="Staff" asp-action="Delete" asp-route-id="@staff.Id">Delete</a>
                </td>
        </tr>
        }
    
</table>

<a class="btn btn-secondary" asp-controller="Staff" asp-action="Create">Add Staff</a>

Views/Staff/ViewStaff.cshtml
@{
    ViewData["Title"] = "Staff Profile";
    string imageUrl = "https://robohash.org/" + @Model.FirstName + "?size=500x500&set=set3";
}

<style>
    .bg-image {
        background-image: url('https://th.bing.com/th/id/R.39ee609d2381b1246bf0580f7740f69f?rik=uWfvRen2526XBQ&riu=http%3a%2f%2fak3.picdn.net%2fshutterstock%2fvideos%2f3644588%2fthumb%2f1.jpg%3fi10c%3dimg.resize(height%3a160)&ehk=3lzP8SotVUTHlmAYI2IFXcwlchIBkTqXudwQSLUHtww%3d&risl=&pid=ImgRaw&r=0');
        background-size: cover;
        background-position: center;
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
    }

    .bg-overlay {
        background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5));
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        z-index: -1;
    }
</style>

<div class="bg-image"></div>
<div class="bg-overlay"></div>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card shadow-lg border-0 rounded-lg mt-5">
                <div class="card-header">
                    <h3 class="text-center font-weight-light mt-4"><span>@Model.FirstName @Model.LastName</span>'s Profile</h3>
                    <p class="text-center font-weight-light mb-4">ID No: @Model.Id</p>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img src=@imageUrl class="rounded-circle bordered w-25 border-8 img-responsive" alt="Profile Picture" />
                    </div>
                    <div class="mt-2">
                        <h5 class="text-center">@Model.FirstName @Model.LastName</h5>
                        <p class="text-center mt-1">Age: @Model.Age</p>
                        <p class="text-center mt-1 text-sm-center">ID: @Model.Id</p>

                    </div>
                </div>
                <div class="card-footer text-center">
                    <div class="btn-group" role="group" aria-label="Profile Actions">
                        <a asp-controller="Staff" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-primary mx-1">Edit Profile</a>
                        <a asp-controller="Staff" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-sm btn-danger mx-1">Delete Profile</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>